test_pod:
  image: bats/bats:v1.1.0
  pullPolicy: IfNotPresent

loki:
  enabled: false

promtail:
  enabled: true
  extraArgs: []
    
  image:
    # -- The Docker registry
    registry: harbor.mustafar.lol
    # -- Docker image repository
    repository: grafana/promtail
    # -- Overrides the image tag whose default is the chart's appVersion
    tag: 2.6.1
    # -- Docker image pull policy
    pullPolicy: IfNotPresent
  config:
    # -- The log level of the Promtail server
    # Must be reference in `config.file` to configure `server.log_level`
    # See default config in `values.yaml`
    logLevel: info
    # -- The port of the Promtail server
    # Must be reference in `config.file` to configure `server.http_listen_port`
    # See default config in `values.yaml`
    serverPort: 3101
    # -- The config of clients of the Promtail server
    # Must be reference in `config.file` to configure `clients`
    # @default -- See `values.yaml`
    clients:
      - url: https://loki.svc.mustafar.lol/loki/api/v1/push
        tls_config:
          insecure_skip_verify: true
    
    snippets:
      pipelineStages:
      - cri: {}
      - json:
        expressions:
        is_even: is_even
        level: level
        version: version
      # - static_labels:
      #     cluster: services-shared
      # scrapeConfigs: |
      #   # See also https://github.com/grafana/loki/blob/master/production/ksonnet/promtail/scrape_config.libsonnet for reference
      #   - job_name: kubernetes-pods
      #     pipeline_stages:
      #       {{- toYaml .Values.config.snippets.pipelineStages | nindent 4 }}
      #       - some-shit
      #     kubernetes_sd_configs:
      #       - role: pod
      #     relabel_configs:
      #       - source_labels:
      #           - __meta_kubernetes_pod_controller_name
      #         regex: ([0-9a-z-.]+?)(-[0-9a-f]{8,10})?
      #         action: replace
      #         target_label: __tmp_controller_name
      #       - source_labels:
      #           - __meta_kubernetes_pod_label_app_kubernetes_io_name
      #           - __meta_kubernetes_pod_label_app
      #           - __tmp_controller_name
      #           - __meta_kubernetes_pod_name
      #         regex: ^;*([^;]+)(;.*)?$
      #         action: replace
      #         target_label: app
      #       - source_labels:
      #           - __meta_kubernetes_pod_label_app_kubernetes_io_instance
      #           - __meta_kubernetes_pod_label_release
      #         regex: ^;*([^;]+)(;.*)?$
      #         action: replace
      #         target_label: instance
      #       - source_labels:
      #           - __meta_kubernetes_pod_label_app_kubernetes_io_component
      #           - __meta_kubernetes_pod_label_component
      #         regex: ^;*([^;]+)(;.*)?$
      #         action: replace
      #         target_label: component
      #       {{- if .Values.config.snippets.addScrapeJobLabel }}
      #       - replacement: kubernetes-pods
      #         target_label: scrape_job
      #       {{- end }}
      #       {{- toYaml .Values.config.snippets.common | nindent 4 }}
      #       {{- with .Values.config.snippets.extraRelabelConfigs }}
      #       {{- toYaml . | nindent 4 }}
      #       {{- end }}